# Generated by Django 6.0.1 on 2026-01-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=100)),
                ('num_questions', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField()),
                ('password_hash', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.CharField()),
                ('answer1', models.CharField()),
                ('answer2', models.CharField()),
                ('answer3', models.CharField()),
                ('answer_r', models.CharField()),
                ('quiz_id', models.ManyToManyField(to='anime_app.quizzes')),
            ],
        ),
    ]
