# Generated by Django 6.0.1 on 2026-01-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
